//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolloVerdeEntities : DbContext
    {
        public PolloVerdeEntities()
            : base("name=PolloVerdeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cliente> tb_cliente { get; set; }
        public virtual DbSet<tb_combo> tb_combo { get; set; }
        public virtual DbSet<tb_detalle_factura> tb_detalle_factura { get; set; }
        public virtual DbSet<tb_encuesta> tb_encuesta { get; set; }
        public virtual DbSet<tb_factura> tb_factura { get; set; }
        public virtual DbSet<tb_menu> tb_menu { get; set; }
        public virtual DbSet<tb_pregunta_encuesta> tb_pregunta_encuesta { get; set; }
        public virtual DbSet<tb_producto> tb_producto { get; set; }
        public virtual DbSet<tb_proveedor> tb_proveedor { get; set; }
        public virtual DbSet<tb_region> tb_region { get; set; }
        public virtual DbSet<tb_respuesta_encuesta> tb_respuesta_encuesta { get; set; }
        public virtual DbSet<tb_sucursal> tb_sucursal { get; set; }
        public virtual DbSet<tb_tipo_pago> tb_tipo_pago { get; set; }
        public virtual DbSet<tb_tipo_producto> tb_tipo_producto { get; set; }
    }
}
