//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detalle_factura
    {
        public int id_detalle_factura { get; set; }
        public int id_factura { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual tb_factura tb_factura { get; set; }
        public virtual tb_producto tb_producto { get; set; }
    }
}
