//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_encuesta()
        {
            this.tb_respuesta_encuesta = new HashSet<tb_respuesta_encuesta>();
        }
    
        public int id_encuesta { get; set; }
        public System.DateTime fecha_encuesta { get; set; }
        public int id_cliente { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_respuesta_encuesta> tb_respuesta_encuesta { get; set; }
    }
}
