//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_factura()
        {
            this.tb_detalle_factura = new HashSet<tb_detalle_factura>();
        }
    
        public int id_factura { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public int descuento_aplicado { get; set; }
        public int id_tipo_pago { get; set; }
        public int id_cliente { get; set; }
        public int id_sucursal { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalle_factura> tb_detalle_factura { get; set; }
        public virtual tb_sucursal tb_sucursal { get; set; }
        public virtual tb_tipo_pago tb_tipo_pago { get; set; }
    }
}
