//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_menu
    {
        public int id_menu { get; set; }
        public string descripcion_menu { get; set; }
        public int id_producto { get; set; }
        public int id_combo { get; set; }
    
        public virtual tb_combo tb_combo { get; set; }
        public virtual tb_producto tb_producto { get; set; }
    }
}
