//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_producto()
        {
            this.tb_detalle_factura = new HashSet<tb_detalle_factura>();
            this.tb_menu = new HashSet<tb_menu>();
        }
    
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion_producto { get; set; }
        public int precio_producto { get; set; }
        public int cantidad_producto { get; set; }
        public int id_tipo_producto { get; set; }
        public int id_proveedor { get; set; }
        public int id_sucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_detalle_factura> tb_detalle_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_menu> tb_menu { get; set; }
        public virtual tb_proveedor tb_proveedor { get; set; }
        public virtual tb_sucursal tb_sucursal { get; set; }
        public virtual tb_tipo_producto tb_tipo_producto { get; set; }
    }
}
