//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_respuesta_encuesta
    {
        public int id_respuesta_encuesta { get; set; }
        public string descripcion_respuesta { get; set; }
        public int id_encuesta { get; set; }
        public int id_pregunta_encuesta { get; set; }
    
        public virtual tb_encuesta tb_encuesta { get; set; }
        public virtual tb_pregunta_encuesta tb_pregunta_encuesta { get; set; }
    }
}
