//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolloVerde.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_sucursal()
        {
            this.tb_factura = new HashSet<tb_factura>();
            this.tb_producto = new HashSet<tb_producto>();
            this.tb_proveedor = new HashSet<tb_proveedor>();
        }
    
        public int id_sucursal { get; set; }
        public string descripcion_sucursal { get; set; }
        public int id_region { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_factura> tb_factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_producto> tb_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_proveedor> tb_proveedor { get; set; }
        public virtual tb_region tb_region { get; set; }
    }
}
